In [12]:
from collections import deque
import torch
import numpy as np

In [13]:
inputs = deque(maxlen=12)

In [14]:
print(inputs)

deque([], maxlen=12)


In [15]:
print(len(inputs))

0


In [18]:
for i in range(10):
    inputs.append(i)
print(inputs)

deque([3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=12)


In [19]:
print(inputs[-1])

9


In [21]:
if 10 in inputs:
    print("in")

In [23]:
t = [[] for _ in range(12)]

In [24]:
t

[[], [], [], [], [], [], [], [], [], [], [], []]

In [27]:
tt = []

In [28]:
[tt.append([]) for _ in range(12)]

[None, None, None, None, None, None, None, None, None, None, None, None]

In [29]:
tt

[[], [], [], [], [], [], [], [], [], [], [], []]

In [30]:
jobcounters = [0 for _ in range(12)]

In [31]:
jobcounters

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [72]:
s_t_list = [None for _ in range(12)]
s_t_list[0] = torch.tensor(list(np.zeros((2, 3))), dtype=torch.float)

In [73]:
s_t_list

[tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [34]:
t = [1,2,3,4]
t

[1, 2, 3, 4]

In [64]:
t = list([0,1,0,0])
tt = [0, 1, 0, 0]
print(t)
print(tt)
print(type(t))
print(type(tt))

[0, 1, 0, 0]
[0, 1, 0, 0]
<class 'list'>
<class 'list'>


In [63]:
list([t[i] = t[i]+1 for i in t if t[i]>0])

SyntaxError: invalid syntax (<ipython-input-63-a83ae321a629>, line 1)

In [65]:
t[t > 0 ] += 1

TypeError: '>' not supported between instances of 'list' and 'int'

In [66]:
t = np.array(t)

In [67]:
t[t > 0 ] += 1

In [68]:
t

array([0, 2, 0, 0])

In [74]:
s_t_list

[tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [75]:
for jobnumber in range(len(s_t_list)):
    if not s_t_list[jobnumber] is None:
        print("!!!!")

!!!!


In [76]:
len(s_t_list)

12

In [78]:
s_t_list[0].flatten()

tensor([0., 0., 0., 0., 0., 0.])

In [79]:
jc = np.array([2,1,0,0,0,1])

In [80]:
jc = np.array([])

In [81]:
len(jc)

0

In [91]:
jc=np.append(jc, 2)

In [92]:
jc

array([1., 2.])

In [93]:
len(jc)

2

In [99]:
if not 1 in jc:
    print("test")

In [100]:
jc[-1]

2.0

In [101]:
t = [1,2,3]

In [103]:
for i in range(len(t)):
    print(i)

0
1
2


In [104]:
inputs = deque(maxlen=12)

In [105]:
[inputs.append(torch.tensor(list(np.zeros((10 * 5))), dtype=torch.float))
         for _ in range(12)]

[None, None, None, None, None, None, None, None, None, None, None, None]

In [106]:
inputs

deque([tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0.]),
       tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0.]),
       tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0.]),
       tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0.]),
       tenso

In [107]:
inputs.append(1)

In [108]:
inputs

deque([tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0.]),
       tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0.]),
       tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0.]),
       tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
               0., 0.]),
       tenso

In [109]:
entire_job_list = deque(maxlen=12)


In [115]:
entire_job_list

deque([1, 2])

In [113]:
entire_job_list.append(2)

In [116]:
s_t_list = np.array([None for _ in range(12)])

In [118]:
s_t_list[0] = 1

In [122]:
s_t_list[len(s_t_list)-1]

In [123]:
s_t_list

array([1, None, None, None, None, None, None, None, None, None, None,
       None], dtype=object)

In [127]:
s = Counter()

s = Counter({0:s_t_list[0], 1:s_t_list[1]})


NameError: name 'Counter' is not defined

In [142]:
a=[1,2,3,1, 6, 0,0 ,0]
b=[]
print(list(set(b) - set(a)))

[]


In [144]:
b.append(7)

In [145]:
print(list(set(b) - set(a)))

[7]


In [146]:
b

[1, 7]

In [147]:
inputs = [torch.tensor(list(np.zeros((2 * 3))), dtype=torch.float) for _ in range(12)]

In [148]:
inputs

[tensor([0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0.])]

In [149]:
a,b

([1, 2, 3, 1, 6, 0, 0, 0], [1, 7])

In [154]:
if set(c)-set(a):
    print("!!")

In [152]:
c = [0,1]

In [155]:
a.flatten()

AttributeError: 'list' object has no attribute 'flatten'

In [156]:
aa = np.array(a)

In [157]:
aa

array([1, 2, 3, 1, 6, 0, 0, 0])

In [158]:
aa.flatten()

array([1, 2, 3, 1, 6, 0, 0, 0])

In [159]:
a[0] = torch.tensor(1)

In [160]:
a

[tensor(1), 2, 3, 1, 6, 0, 0, 0]

In [161]:
a[0].flatten()

tensor(1)

In [162]:
a

[tensor(1), 2, 3, 1, 6, 0, 0, 0]

In [163]:
b

[1, 7]

In [164]:
a = b

In [165]:
a

[1, 7]

In [166]:
b[0] =2

In [167]:
b

[2, 7]

In [168]:
a

[2, 7]