In [1]:
import numpy as np
import torch
np.set_printoptions(precision=3)

In [2]:
mat = np.random.random((10,10))
# mat = torch.tensor(dist, dtype=torch.float)

In [3]:
mask = np.zeros((10,10))
for i in range(8): 
    for ii in range(7):
        mask[i][ii] = 1
# mask = torch.tensor(mask, dtype=torch.float)

In [4]:
mat, mask

(array([[0.197, 0.971, 0.544, 0.356, 0.662, 0.19 , 0.32 , 0.25 , 0.135,
         0.598],
        [0.895, 0.609, 0.101, 0.24 , 0.904, 0.531, 0.352, 0.63 , 0.036,
         0.419],
        [0.516, 0.247, 0.408, 0.976, 0.234, 0.322, 0.603, 0.889, 0.216,
         0.638],
        [0.708, 0.106, 0.798, 0.378, 0.061, 0.774, 0.47 , 0.221, 0.045,
         0.229],
        [0.329, 0.67 , 0.386, 0.928, 0.62 , 0.796, 0.912, 0.977, 0.436,
         0.918],
        [0.753, 0.131, 0.974, 0.404, 0.678, 0.901, 0.643, 0.894, 0.496,
         0.027],
        [0.558, 0.038, 0.685, 0.533, 0.481, 0.12 , 0.662, 0.135, 0.748,
         0.425],
        [0.358, 0.672, 0.169, 0.22 , 0.87 , 0.559, 0.698, 0.187, 0.332,
         0.361],
        [0.9  , 0.592, 0.615, 0.864, 0.206, 0.142, 0.48 , 0.859, 0.687,
         0.691],
        [0.92 , 0.741, 0.06 , 0.821, 0.307, 0.549, 0.736, 0.06 , 0.526,
         0.454]]), array([[1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
        [

In [5]:
new_mat = np.multiply(mat, mask)
new_mat

array([[0.197, 0.971, 0.544, 0.356, 0.662, 0.19 , 0.32 , 0.   , 0.   ,
        0.   ],
       [0.895, 0.609, 0.101, 0.24 , 0.904, 0.531, 0.352, 0.   , 0.   ,
        0.   ],
       [0.516, 0.247, 0.408, 0.976, 0.234, 0.322, 0.603, 0.   , 0.   ,
        0.   ],
       [0.708, 0.106, 0.798, 0.378, 0.061, 0.774, 0.47 , 0.   , 0.   ,
        0.   ],
       [0.329, 0.67 , 0.386, 0.928, 0.62 , 0.796, 0.912, 0.   , 0.   ,
        0.   ],
       [0.753, 0.131, 0.974, 0.404, 0.678, 0.901, 0.643, 0.   , 0.   ,
        0.   ],
       [0.558, 0.038, 0.685, 0.533, 0.481, 0.12 , 0.662, 0.   , 0.   ,
        0.   ],
       [0.358, 0.672, 0.169, 0.22 , 0.87 , 0.559, 0.698, 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ]])

In [6]:
new_mat_t = torch.tensor(new_mat, dtype=torch.float)

In [7]:
dist_t = torch.exp(new_mat_t)

In [8]:
dist_t

tensor([[1.2174, 2.6412, 1.7232, 1.4275, 1.9381, 1.2095, 1.3769, 1.0000, 1.0000,
         1.0000],
        [2.4481, 1.8381, 1.1063, 1.2711, 2.4684, 1.7011, 1.4216, 1.0000, 1.0000,
         1.0000],
        [1.6761, 1.2796, 1.5044, 2.6538, 1.2636, 1.3795, 1.8280, 1.0000, 1.0000,
         1.0000],
        [2.0303, 1.1116, 2.2207, 1.4587, 1.0628, 2.1692, 1.6005, 1.0000, 1.0000,
         1.0000],
        [1.3894, 1.9544, 1.4714, 2.5295, 1.8597, 2.2160, 2.4886, 1.0000, 1.0000,
         1.0000],
        [2.1232, 1.1403, 2.6495, 1.4975, 1.9703, 2.4616, 1.9014, 1.0000, 1.0000,
         1.0000],
        [1.7466, 1.0388, 1.9838, 1.7034, 1.6175, 1.1278, 1.9395, 1.0000, 1.0000,
         1.0000],
        [1.4303, 1.9581, 1.1836, 1.2458, 2.3859, 1.7485, 2.0094, 1.0000, 1.0000,
         1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000]])

In [9]:
new_dist_t = torch.exp(dist_t)

In [10]:
new_dist_t[dist_t==1] = 0

In [11]:
dist_t, new_dist_t

(tensor([[1.2174, 2.6412, 1.7232, 1.4275, 1.9381, 1.2095, 1.3769, 1.0000, 1.0000,
          1.0000],
         [2.4481, 1.8381, 1.1063, 1.2711, 2.4684, 1.7011, 1.4216, 1.0000, 1.0000,
          1.0000],
         [1.6761, 1.2796, 1.5044, 2.6538, 1.2636, 1.3795, 1.8280, 1.0000, 1.0000,
          1.0000],
         [2.0303, 1.1116, 2.2207, 1.4587, 1.0628, 2.1692, 1.6005, 1.0000, 1.0000,
          1.0000],
         [1.3894, 1.9544, 1.4714, 2.5295, 1.8597, 2.2160, 2.4886, 1.0000, 1.0000,
          1.0000],
         [2.1232, 1.1403, 2.6495, 1.4975, 1.9703, 2.4616, 1.9014, 1.0000, 1.0000,
          1.0000],
         [1.7466, 1.0388, 1.9838, 1.7034, 1.6175, 1.1278, 1.9395, 1.0000, 1.0000,
          1.0000],
         [1.4303, 1.9581, 1.1836, 1.2458, 2.3859, 1.7485, 2.0094, 1.0000, 1.0000,
          1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
          1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         

In [12]:
import sys
new2_dist_t = torch.exp(dist_t)
new2_dist_t[dist_t==1] = sys.maxsize

In [13]:
dist_t, new_dist_t, new2_dist_t

(tensor([[1.2174, 2.6412, 1.7232, 1.4275, 1.9381, 1.2095, 1.3769, 1.0000, 1.0000,
          1.0000],
         [2.4481, 1.8381, 1.1063, 1.2711, 2.4684, 1.7011, 1.4216, 1.0000, 1.0000,
          1.0000],
         [1.6761, 1.2796, 1.5044, 2.6538, 1.2636, 1.3795, 1.8280, 1.0000, 1.0000,
          1.0000],
         [2.0303, 1.1116, 2.2207, 1.4587, 1.0628, 2.1692, 1.6005, 1.0000, 1.0000,
          1.0000],
         [1.3894, 1.9544, 1.4714, 2.5295, 1.8597, 2.2160, 2.4886, 1.0000, 1.0000,
          1.0000],
         [2.1232, 1.1403, 2.6495, 1.4975, 1.9703, 2.4616, 1.9014, 1.0000, 1.0000,
          1.0000],
         [1.7466, 1.0388, 1.9838, 1.7034, 1.6175, 1.1278, 1.9395, 1.0000, 1.0000,
          1.0000],
         [1.4303, 1.9581, 1.1836, 1.2458, 2.3859, 1.7485, 2.0094, 1.0000, 1.0000,
          1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
          1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         