In [1]:
import numpy as np
import torch

In [2]:
mat = np.random.random((10,10))
# mat = torch.tensor(dist, dtype=torch.float)

In [3]:
mask = np.zeros((10,10))
for i in range(8): 
    for ii in range(7):
        mask[i][ii] = 1
# mask = torch.tensor(mask, dtype=torch.float)

In [4]:
mat, mask

(array([[0.291057  , 0.18126351, 0.72779764, 0.273392  , 0.35352037,
         0.8510844 , 0.07952439, 0.66787585, 0.28648662, 0.95905292],
        [0.04853411, 0.03165979, 0.96655152, 0.51222269, 0.20851903,
         0.01652812, 0.25699005, 0.62277403, 0.1697422 , 0.96488752],
        [0.58566378, 0.5952325 , 0.71536619, 0.38592436, 0.43442832,
         0.99055624, 0.35896679, 0.86757931, 0.23849512, 0.3020219 ],
        [0.92467172, 0.82214001, 0.37244432, 0.72303856, 0.28130954,
         0.87313446, 0.39355178, 0.23241097, 0.22814649, 0.95502596],
        [0.32339535, 0.62021836, 0.06351888, 0.34196225, 0.28242452,
         0.82883144, 0.96837936, 0.95840717, 0.80283195, 0.90688701],
        [0.13548336, 0.89732148, 0.19553025, 0.06366457, 0.0823818 ,
         0.40707853, 0.85735843, 0.21042243, 0.32024393, 0.23310713],
        [0.28130165, 0.23387804, 0.58376427, 0.85874237, 0.24250377,
         0.17860155, 0.49190912, 0.76150529, 0.90065799, 0.18299412],
        [0.93025542, 0.7072

In [51]:
# dist = torch.exp(mat)
# dist

In [52]:
# dist.multinomial(num_samples=1)

In [54]:
new_mat = np.multiply(mat, mask)
new_mat

array([[0.89148003, 0.32850352, 0.44024425, 0.40775845, 0.88376463,
        0.80675569, 0.94119437, 0.        , 0.        , 0.        ],
       [0.27763064, 0.63379166, 0.78325036, 0.07566133, 0.02367148,
        0.21385544, 0.47559078, 0.        , 0.        , 0.        ],
       [0.69929315, 0.70063702, 0.24783882, 0.72345597, 0.32574058,
        0.2977381 , 0.38432996, 0.        , 0.        , 0.        ],
       [0.46284557, 0.53134699, 0.768517  , 0.55559356, 0.68216615,
        0.07217367, 0.9505006 , 0.        , 0.        , 0.        ],
       [0.96467249, 0.91145274, 0.41826669, 0.3862651 , 0.98847964,
        0.19393499, 0.15118063, 0.        , 0.        , 0.        ],
       [0.90601128, 0.93348558, 0.94495637, 0.82959234, 0.1973604 ,
        0.92139937, 0.94175747, 0.        , 0.        , 0.        ],
       [0.07244663, 0.23536695, 0.86204711, 0.61182881, 0.1119726 ,
        0.62699342, 0.44556676, 0.        , 0.        , 0.        ],
       [0.0840237 , 0.96975959, 0.5869865

In [57]:
for i in range(len(new_mat)):
    for ii in range(len(new_mat[i])):
        if new_mat[i][ii] == 0:
            new_mat[i][ii] = float('inf')

In [58]:
new_mat

array([[0.89148003, 0.32850352, 0.44024425, 0.40775845, 0.88376463,
        0.80675569, 0.94119437,        inf,        inf,        inf],
       [0.27763064, 0.63379166, 0.78325036, 0.07566133, 0.02367148,
        0.21385544, 0.47559078,        inf,        inf,        inf],
       [0.69929315, 0.70063702, 0.24783882, 0.72345597, 0.32574058,
        0.2977381 , 0.38432996,        inf,        inf,        inf],
       [0.46284557, 0.53134699, 0.768517  , 0.55559356, 0.68216615,
        0.07217367, 0.9505006 ,        inf,        inf,        inf],
       [0.96467249, 0.91145274, 0.41826669, 0.3862651 , 0.98847964,
        0.19393499, 0.15118063,        inf,        inf,        inf],
       [0.90601128, 0.93348558, 0.94495637, 0.82959234, 0.1973604 ,
        0.92139937, 0.94175747,        inf,        inf,        inf],
       [0.07244663, 0.23536695, 0.86204711, 0.61182881, 0.1119726 ,
        0.62699342, 0.44556676,        inf,        inf,        inf],
       [0.0840237 , 0.96975959, 0.5869865

In [59]:
new_mat_t = torch.tensor(new_mat, dtype=torch.float)

In [61]:
dist_t = torch.exp(new_mat_t)

In [62]:
dist_t.multinomial(num_samples=1)

RuntimeError: invalid argument 2: invalid multinomial distribution (encountering probability entry = infinity or NaN) at /Users/soumith/b101_2/2019_02_08/wheel_build_dirs/wheel_3.6/pytorch/aten/src/TH/generic/THTensorRandom.cpp:302