In [1]:
import numpy as np
import torch

In [2]:
mat = np.random.random((16,10))
# mat = torch.tensor(dist, dtype=torch.float)

In [3]:
mask = np.zeros((10,10))
for i in range(8): 
    for ii in range(7):
        mask[i][ii] = 1
# mask = torch.tensor(mask, dtype=torch.float)

In [4]:
mat, mask

(array([[0.76999196, 0.60062618, 0.64705546, 0.61318547, 0.74351238,
         0.98766363, 0.89587192, 0.84966197, 0.79080416, 0.50125411],
        [0.80416935, 0.50852424, 0.05858132, 0.61499884, 0.60993858,
         0.15169379, 0.23373854, 0.70938153, 0.40179558, 0.12354949],
        [0.50658287, 0.86694389, 0.95628939, 0.53312892, 0.66302756,
         0.43026774, 0.34213961, 0.01612412, 0.37057024, 0.39477213],
        [0.75143257, 0.18211303, 0.91560043, 0.44799392, 0.74123455,
         0.69080395, 0.45455177, 0.49371294, 0.08136632, 0.91429785],
        [0.0232368 , 0.50001639, 0.52186349, 0.41890703, 0.56139752,
         0.07400649, 0.01502371, 0.58036401, 0.60491398, 0.54126096],
        [0.01889308, 0.06554541, 0.1660194 , 0.02484215, 0.03861525,
         0.86697097, 0.00099624, 0.10496223, 0.4082879 , 0.27602715],
        [0.15245346, 0.24870845, 0.65147483, 0.20211599, 0.33255907,
         0.71314997, 0.1217749 , 0.34511279, 0.79423561, 0.55621824],
        [0.84471608, 0.1315

In [5]:
# dist = torch.exp(mat)
# dist

In [6]:
# dist.multinomial(num_samples=1)

In [7]:
new_mat = np.multiply(mat, mask)
new_mat

array([[0.76999196, 0.60062618, 0.64705546, 0.61318547, 0.74351238,
        0.98766363, 0.89587192, 0.        , 0.        , 0.        ],
       [0.80416935, 0.50852424, 0.05858132, 0.61499884, 0.60993858,
        0.15169379, 0.23373854, 0.        , 0.        , 0.        ],
       [0.50658287, 0.86694389, 0.95628939, 0.53312892, 0.66302756,
        0.43026774, 0.34213961, 0.        , 0.        , 0.        ],
       [0.75143257, 0.18211303, 0.91560043, 0.44799392, 0.74123455,
        0.69080395, 0.45455177, 0.        , 0.        , 0.        ],
       [0.0232368 , 0.50001639, 0.52186349, 0.41890703, 0.56139752,
        0.07400649, 0.01502371, 0.        , 0.        , 0.        ],
       [0.01889308, 0.06554541, 0.1660194 , 0.02484215, 0.03861525,
        0.86697097, 0.00099624, 0.        , 0.        , 0.        ],
       [0.15245346, 0.24870845, 0.65147483, 0.20211599, 0.33255907,
        0.71314997, 0.1217749 , 0.        , 0.        , 0.        ],
       [0.84471608, 0.13156841, 0.1615619

In [8]:
# for i in range(len(new_mat)):
#     for ii in range(len(new_mat[i])):
#         if new_mat[i][ii] == 0:
#             new_mat[i][ii] = float('inf')

In [9]:
new_mat

array([[0.76999196, 0.60062618, 0.64705546, 0.61318547, 0.74351238,
        0.98766363, 0.89587192, 0.        , 0.        , 0.        ],
       [0.80416935, 0.50852424, 0.05858132, 0.61499884, 0.60993858,
        0.15169379, 0.23373854, 0.        , 0.        , 0.        ],
       [0.50658287, 0.86694389, 0.95628939, 0.53312892, 0.66302756,
        0.43026774, 0.34213961, 0.        , 0.        , 0.        ],
       [0.75143257, 0.18211303, 0.91560043, 0.44799392, 0.74123455,
        0.69080395, 0.45455177, 0.        , 0.        , 0.        ],
       [0.0232368 , 0.50001639, 0.52186349, 0.41890703, 0.56139752,
        0.07400649, 0.01502371, 0.        , 0.        , 0.        ],
       [0.01889308, 0.06554541, 0.1660194 , 0.02484215, 0.03861525,
        0.86697097, 0.00099624, 0.        , 0.        , 0.        ],
       [0.15245346, 0.24870845, 0.65147483, 0.20211599, 0.33255907,
        0.71314997, 0.1217749 , 0.        , 0.        , 0.        ],
       [0.84471608, 0.13156841, 0.1615619

In [10]:
new_mat_t = torch.tensor(new_mat, dtype=torch.float)

In [61]:
dist_t = torch.exp(new_mat_t)

In [62]:
dist_t.multinomial(num_samples=1)

RuntimeError: invalid argument 2: invalid multinomial distribution (encountering probability entry = infinity or NaN) at /Users/soumith/b101_2/2019_02_08/wheel_build_dirs/wheel_3.6/pytorch/aten/src/TH/generic/THTensorRandom.cpp:302

In [1]:
len(new_mat)

NameError: name 'new_mat' is not defined

In [11]:
new_mat_t

tensor([[0.7700, 0.6006, 0.6471, 0.6132, 0.7435, 0.9877, 0.8959, 0.0000, 0.0000,
         0.0000],
        [0.8042, 0.5085, 0.0586, 0.6150, 0.6099, 0.1517, 0.2337, 0.0000, 0.0000,
         0.0000],
        [0.5066, 0.8669, 0.9563, 0.5331, 0.6630, 0.4303, 0.3421, 0.0000, 0.0000,
         0.0000],
        [0.7514, 0.1821, 0.9156, 0.4480, 0.7412, 0.6908, 0.4546, 0.0000, 0.0000,
         0.0000],
        [0.0232, 0.5000, 0.5219, 0.4189, 0.5614, 0.0740, 0.0150, 0.0000, 0.0000,
         0.0000],
        [0.0189, 0.0655, 0.1660, 0.0248, 0.0386, 0.8670, 0.0010, 0.0000, 0.0000,
         0.0000],
        [0.1525, 0.2487, 0.6515, 0.2021, 0.3326, 0.7131, 0.1218, 0.0000, 0.0000,
         0.0000],
        [0.8447, 0.1316, 0.1616, 0.1143, 0.7066, 0.8523, 0.8230, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])

In [12]:
new_mat_t.shape

torch.Size([10, 10])