In [1]:
import numpy as np
import torch
np.set_printoptions(precision=3)

In [2]:
mat = np.random.random((10,10))
# mat = torch.tensor(dist, dtype=torch.float)

In [3]:
mask = np.zeros((10,10))
for i in range(8): 
    for ii in range(7):
        mask[i][ii] = 1
# mask = torch.tensor(mask, dtype=torch.float)

In [4]:
mat, mask

(array([[0.608, 0.441, 0.266, 0.451, 0.029, 0.384, 0.497, 0.098, 0.707,
         0.444],
        [0.329, 0.778, 0.066, 0.638, 0.417, 0.439, 0.726, 0.185, 0.472,
         0.568],
        [0.32 , 0.819, 0.607, 0.375, 0.39 , 0.644, 0.863, 0.138, 0.57 ,
         0.493],
        [0.129, 0.796, 0.538, 0.246, 0.194, 0.427, 0.395, 0.336, 0.782,
         0.255],
        [0.855, 0.904, 0.602, 0.239, 0.017, 0.542, 0.138, 0.688, 0.841,
         0.637],
        [0.681, 0.484, 0.68 , 0.898, 0.665, 0.234, 0.489, 0.121, 0.88 ,
         0.304],
        [0.939, 0.515, 0.208, 0.479, 0.374, 0.222, 0.383, 0.815, 0.672,
         0.999],
        [0.867, 0.662, 0.272, 0.162, 0.034, 0.172, 0.255, 0.335, 0.509,
         0.792],
        [0.959, 0.26 , 0.33 , 0.022, 0.8  , 0.518, 0.928, 0.915, 0.509,
         0.081],
        [0.84 , 0.532, 0.9  , 0.631, 0.02 , 0.828, 0.469, 0.356, 0.364,
         0.626]]), array([[1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
        [

In [9]:
new_mat = np.multiply(mat, mask)
new_mat_t = torch.tensor(new_mat, dtype=torch.float)

In [13]:
dist_t = torch.exp(new_mat_t)
dist_t2 = torch.exp(new_mat_t)

In [14]:
dist_t

tensor([[1.8374, 1.5547, 1.3043, 1.5695, 1.0297, 1.4675, 1.6436, 1.0000, 1.0000,
         1.0000],
        [1.3898, 2.1778, 1.0683, 1.8931, 1.5170, 1.5516, 2.0659, 1.0000, 1.0000,
         1.0000],
        [1.3778, 2.2682, 1.8345, 1.4551, 1.4776, 1.9045, 2.3709, 1.0000, 1.0000,
         1.0000],
        [1.1380, 2.2177, 1.7124, 1.2787, 1.2145, 1.5319, 1.4848, 1.0000, 1.0000,
         1.0000],
        [2.3520, 2.4692, 1.8251, 1.2701, 1.0176, 1.7195, 1.1475, 1.0000, 1.0000,
         1.0000],
        [1.9768, 1.6221, 1.9733, 2.4540, 1.9441, 1.2642, 1.6309, 1.0000, 1.0000,
         1.0000],
        [2.5565, 1.6742, 1.2310, 1.6141, 1.4539, 1.2486, 1.4671, 1.0000, 1.0000,
         1.0000],
        [2.3802, 1.9378, 1.3130, 1.1762, 1.0349, 1.1875, 1.2898, 1.0000, 1.0000,
         1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000]])

In [15]:
dist_t.multinomial(num_samples=1)

tensor([[3],
        [0],
        [5],
        [2],
        [8],
        [5],
        [7],
        [2],
        [8],
        [8]])

In [16]:
dist_t2[dist_t2==1] = 0
dist_t2

tensor([[1.8374, 1.5547, 1.3043, 1.5695, 1.0297, 1.4675, 1.6436, 0.0000, 0.0000,
         0.0000],
        [1.3898, 2.1778, 1.0683, 1.8931, 1.5170, 1.5516, 2.0659, 0.0000, 0.0000,
         0.0000],
        [1.3778, 2.2682, 1.8345, 1.4551, 1.4776, 1.9045, 2.3709, 0.0000, 0.0000,
         0.0000],
        [1.1380, 2.2177, 1.7124, 1.2787, 1.2145, 1.5319, 1.4848, 0.0000, 0.0000,
         0.0000],
        [2.3520, 2.4692, 1.8251, 1.2701, 1.0176, 1.7195, 1.1475, 0.0000, 0.0000,
         0.0000],
        [1.9768, 1.6221, 1.9733, 2.4540, 1.9441, 1.2642, 1.6309, 0.0000, 0.0000,
         0.0000],
        [2.5565, 1.6742, 1.2310, 1.6141, 1.4539, 1.2486, 1.4671, 0.0000, 0.0000,
         0.0000],
        [2.3802, 1.9378, 1.3130, 1.1762, 1.0349, 1.1875, 1.2898, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])

In [23]:
#dist_t2.multinomial(num_samples=1)
# dist_t3 = torch.exp(new_mat_t)
# dist_t3[dist_t3==1] = 0
# dist_t3.multinomial(num_samples=1)
new_mat_t
new_mat_t.multinomial(num_samples=1)


# dist_t_sam = torch.multinomial(dist_t,num_samples=1)
# #dist_t_sam2 = torch.multinomial(new_dist_t,num_samples=1)

# print(dist_t_sam)
# #print(dist_t_sam2)
#new_dist_t.multinomial(num_samples=1)

RuntimeError: invalid argument 2: invalid multinomial distribution (sum of probabilities <= 0) at ../aten/src/TH/generic/THTensorRandom.cpp:343

In [53]:
torch.multinomial(dist_t,num_samples=1, replacement = True)
dist_t

tensor([[1.9392, 2.2552, 1.5746, 1.1455, 2.5479, 1.3361, 1.4905, 1.0000, 1.0000,
         1.0000],
        [1.5800, 1.6217, 1.4687, 1.4961, 2.1819, 2.4518, 1.4420, 1.0000, 1.0000,
         1.0000],
        [1.7218, 1.1682, 1.6986, 2.6181, 1.8967, 1.4252, 1.4575, 1.0000, 1.0000,
         1.0000],
        [1.9982, 1.3047, 1.2179, 1.1755, 1.2216, 1.1943, 1.0728, 1.0000, 1.0000,
         1.0000],
        [1.7842, 1.0089, 1.9063, 2.4417, 1.6717, 2.3983, 2.0263, 1.0000, 1.0000,
         1.0000],
        [1.3318, 2.5300, 1.4888, 1.9167, 2.2735, 2.1610, 1.2751, 1.0000, 1.0000,
         1.0000],
        [1.1196, 1.5680, 1.1187, 1.1138, 1.8990, 2.5667, 1.1529, 1.0000, 1.0000,
         1.0000],
        [1.4241, 1.0362, 1.0837, 2.6871, 2.0888, 2.0783, 2.1502, 1.0000, 1.0000,
         1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000]])

In [10]:
import sys
new2_dist_t = torch.exp(dist_t)
new2_dist_t[dist_t==1] = sys.maxsize

In [11]:
dist_t, new_dist_t, new2_dist_t

(tensor([[2.0244, 1.9441, 1.7483, 1.3210, 1.4235, 1.1437, 2.4157, 1.0000, 1.0000,
          1.0000],
         [2.1274, 1.3547, 2.0208, 2.1278, 1.9640, 2.5667, 1.4422, 1.0000, 1.0000,
          1.0000],
         [1.9098, 1.2794, 2.3541, 2.0987, 2.4631, 1.8300, 1.9701, 1.0000, 1.0000,
          1.0000],
         [1.8241, 1.0574, 1.0544, 1.9628, 1.1312, 2.5016, 1.2817, 1.0000, 1.0000,
          1.0000],
         [1.6568, 2.0768, 1.4259, 2.5657, 1.8061, 1.5790, 2.5048, 1.0000, 1.0000,
          1.0000],
         [1.9813, 1.3265, 1.0915, 1.8365, 1.0073, 2.5797, 2.0981, 1.0000, 1.0000,
          1.0000],
         [1.3010, 2.1887, 1.2371, 2.4385, 2.4771, 1.6575, 1.5402, 1.0000, 1.0000,
          1.0000],
         [1.0864, 2.1722, 2.6665, 1.8781, 2.2712, 1.4836, 1.1685, 1.0000, 1.0000,
          1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
          1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         

In [35]:
torch.multinomial(new_dist_t,num_samples=1)
#new_dist_t.multinomial(num_samples=1)

RuntimeError: invalid argument 2: invalid multinomial distribution (sum of probabilities <= 0) at ../aten/src/TH/generic/THTensorRandom.cpp:343

In [5]:
new_mat = np.multiply(mat, mask)
new_mat

array([[0.96 , 0.563, 0.61 , 0.94 , 0.402, 0.384, 0.403, 0.   , 0.   ,
        0.   ],
       [0.952, 0.931, 0.728, 0.061, 0.817, 0.627, 0.966, 0.   , 0.   ,
        0.   ],
       [0.789, 0.65 , 0.976, 0.026, 0.849, 0.87 , 0.179, 0.   , 0.   ,
        0.   ],
       [0.1  , 0.288, 0.684, 0.723, 0.213, 0.119, 0.673, 0.   , 0.   ,
        0.   ],
       [0.491, 0.071, 0.04 , 0.183, 0.022, 0.727, 0.665, 0.   , 0.   ,
        0.   ],
       [0.355, 0.716, 0.441, 0.527, 0.641, 0.322, 0.599, 0.   , 0.   ,
        0.   ],
       [0.337, 0.257, 0.198, 0.05 , 0.282, 0.533, 0.447, 0.   , 0.   ,
        0.   ],
       [0.347, 0.49 , 0.724, 0.668, 0.541, 0.678, 0.69 , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ]])

In [6]:
new_mat_t = torch.tensor(new_mat, dtype=torch.float)

In [7]:
new_mat_t

tensor([[0.9602, 0.5627, 0.6103, 0.9403, 0.4016, 0.3842, 0.4034, 0.0000, 0.0000,
         0.0000],
        [0.9522, 0.9308, 0.7275, 0.0611, 0.8170, 0.6267, 0.9659, 0.0000, 0.0000,
         0.0000],
        [0.7895, 0.6504, 0.9756, 0.0257, 0.8488, 0.8698, 0.1793, 0.0000, 0.0000,
         0.0000],
        [0.0999, 0.2883, 0.6842, 0.7227, 0.2131, 0.1195, 0.6728, 0.0000, 0.0000,
         0.0000],
        [0.4910, 0.0713, 0.0398, 0.1830, 0.0217, 0.7274, 0.6651, 0.0000, 0.0000,
         0.0000],
        [0.3553, 0.7158, 0.4406, 0.5275, 0.6415, 0.3219, 0.5987, 0.0000, 0.0000,
         0.0000],
        [0.3373, 0.2569, 0.1984, 0.0503, 0.2824, 0.5327, 0.4475, 0.0000, 0.0000,
         0.0000],
        [0.3474, 0.4898, 0.7244, 0.6681, 0.5408, 0.6776, 0.6896, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])

In [8]:
dist_t = torch.exp(new_mat_t)

In [88]:
dist_t

tensor([[1.9392, 2.2552, 1.5746, 1.1455, 2.5479, 1.3361, 1.4905, 1.0000, 1.0000,
         1.0000],
        [1.5800, 1.6217, 1.4687, 1.4961, 2.1819, 2.4518, 1.4420, 1.0000, 1.0000,
         1.0000],
        [1.7218, 1.1682, 1.6986, 2.6181, 1.8967, 1.4252, 1.4575, 1.0000, 1.0000,
         1.0000],
        [1.9982, 1.3047, 1.2179, 1.1755, 1.2216, 1.1943, 1.0728, 1.0000, 1.0000,
         1.0000],
        [1.7842, 1.0089, 1.9063, 2.4417, 1.6717, 2.3983, 2.0263, 1.0000, 1.0000,
         1.0000],
        [1.3318, 2.5300, 1.4888, 1.9167, 2.2735, 2.1610, 1.2751, 1.0000, 1.0000,
         1.0000],
        [1.1196, 1.5680, 1.1187, 1.1138, 1.8990, 2.5667, 1.1529, 1.0000, 1.0000,
         1.0000],
        [1.4241, 1.0362, 1.0837, 2.6871, 2.0888, 2.0783, 2.1502, 1.0000, 1.0000,
         1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000]])