In [1]:
import numpy as np
import torch
from random import *
from sklearn import preprocessing
import pandas as pd
from sklearn.preprocessing import Normalizer

# np.set_printoptions(precision=6)

In [2]:
# mat = np.random.random((16))
mat = np.array([-2.7531, -2.7391, -2.7252, -2.7484, -2.7834, -2.7706, -2.8017, -2.7864, -2.7768, -2.7830, -2.8187, -2.7667, -2.7849, -2.7957, -2.8021, -2.7312])

# Make a mask
mask = np.ones((16))

mask[1] = 0
mask[2] = 0
mask[5] = 0
mask[7] = 0

mat, mask

(array([-2.7531, -2.7391, -2.7252, -2.7484, -2.7834, -2.7706, -2.8017,
        -2.7864, -2.7768, -2.783 , -2.8187, -2.7667, -2.7849, -2.7957,
        -2.8021, -2.7312]),
 array([1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [3]:
# Add min value for making positive values
mat = torch.tensor(mat, dtype=torch.float)
min_v = min(mat)
print(min_v)
m_mat = mat-min_v+0.01
print(m_mat)

tensor(-2.8187)
tensor([0.0756, 0.0896, 0.1035, 0.0803, 0.0453, 0.0581, 0.0270, 0.0423, 0.0519,
        0.0457, 0.0100, 0.0620, 0.0438, 0.0330, 0.0266, 0.0975])


In [4]:
# masking out
masked_mat = np.multiply(m_mat, mask)

# normalization
min_max_scaler = preprocessing.MinMaxScaler()
masked_mat_re = np.reshape(masked_mat,(-1,1))
masked_mat_scaled = min_max_scaler.fit_transform(masked_mat_re)
print(masked_mat_scaled)

[[0.77538546]
 [0.        ]
 [0.        ]
 [0.82358998]
 [0.46461509]
 [0.        ]
 [0.2769224 ]
 [0.        ]
 [0.53230878]
 [0.46871833]
 [0.102564  ]
 [0.63589728]
 [0.4492316 ]
 [0.33846121]
 [0.2728216 ]
 [1.        ]]


In [5]:
_masked_mat_scaled = np.ones((len(masked_mat_scaled),1))

t = np.sum(masked_mat_scaled[:])
_masked_mat_scaled[:] = masked_mat_scaled[:]/t
print(_masked_mat_scaled)
print(np.sum(_masked_mat_scaled[:]))

[[0.12627367]
 [0.        ]
 [0.        ]
 [0.13412391]
 [0.07566385]
 [0.        ]
 [0.04509758]
 [0.        ]
 [0.08668796]
 [0.07633208]
 [0.01670283]
 [0.10355763]
 [0.07315861]
 [0.05511935]
 [0.04442975]
 [0.16285277]]
1.0


In [6]:
_masked_mat_scaled_re = np.reshape(_masked_mat_scaled,len(_masked_mat_scaled))
_masked_mat_scaled_tre = torch.tensor(_masked_mat_scaled_re, dtype=torch.float)
print(_masked_mat_scaled_tre)

tensor([0.1263, 0.0000, 0.0000, 0.1341, 0.0757, 0.0000, 0.0451, 0.0000, 0.0867,
        0.0763, 0.0167, 0.1036, 0.0732, 0.0551, 0.0444, 0.1629])


In [7]:
t = _masked_mat_scaled_tre.multinomial(num_samples=1)
print(t)
print(t[0].item())

tensor([8])
8


In [8]:
for i in range(1000):
    t = _masked_mat_scaled_tre.multinomial(num_samples=1)
    if _masked_mat_scaled_tre[t[0].item()] == 0:
        print("!!!!!!!!!!!!!!!!!")

In [11]:
# Node 클래스 정의
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None


# LinkedList 클래스 (자료구조) 정의
class LinkedList:

    # 초기화 메소드
    def __init__(self):
        dummy = Node("dummy")
        self.head = dummy
        self.tail = dummy

        self.current = None
        self.before = None

        self.num_of_data = 0

    # append 메소드 (insert - 맨 뒤에 노드 추가, tail과 node의 next, 데이터 개수 변경)
    def append(self, data):
        new_node = Node(data)
        self.tail.next = new_node
        self.tail = new_node

        self.num_of_data += 1

    # delete 메소드 (delete - current 노드 삭제, 인접 노드의 current, next 변경, 데이터 개수 변경)
    def delete(self):
        pop_data = self.current.data

        if self.current is self.tail:
            self.tail = self.before

        self.before.next = self.current.next
        self.current = self.before # 중요 : current가 next가 아닌 before로 변경된다.
        #

        self.num_of_data -= 1

        return pop_data

    # first 메소드 (search1 - 맨 앞의 노드 검색, before, current 변경)
    def first(self):
        if self.num_of_data == 0: # 데이터가 없는 경우 첫번째 노드도 없기 때문에 None 리턴
            return None

        self.before = self.head
        self.current = self.head.next

        return self.current.data

    # next 메소드 (search2 - current 노드의 다음 노드 검색, 이전에 first 메소드가 한번은 실행되어야 함)
    def next(self):
        if self.current.next == None:
            return None

        self.before = self.current
        self.current = self.current.next

        return self.current.data

    def size(self):
        return self.num_of_data

In [12]:
l_list = LinkedList()