In [20]:
import numpy as np
import torch
from random import *
from sklearn import preprocessing
import pandas as pd


# np.set_printoptions(precision=6)

In [21]:
mat = np.random.random((16,10))
# mat = torch.tensor(dist, dtype=torch.float)

In [22]:
mat.shape

(16, 10)

In [23]:
# Make a mask
mask = np.ones((16,10))

for i in range(30):
    x = randint(0, 15)
    y = randint(0, 9)
    mask[x][y] = 0

mask[2][1] = 0
mask[2][2] = 0
mask[2][5] = 0
mask[2][7] = 0
mask

array([[1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [0., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 1., 1., 0., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 0.],
       [1., 1., 0., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 0., 0., 1., 0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 0.],
       [1., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 0., 0., 1., 1., 1., 1., 1., 0., 1.],
       [0., 1., 1., 1., 1., 0., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
new_mat_t = torch.tensor(mat, dtype=torch.float)
new_mat_t

tensor([[2.9261e-02, 2.9281e-01, 5.2002e-01, 7.2190e-01, 6.4496e-01, 5.0166e-01,
         5.7265e-01, 3.3640e-01, 1.6257e-01, 1.6744e-02],
        [6.6781e-01, 1.5332e-01, 9.8559e-01, 4.6983e-01, 6.3849e-02, 8.5173e-01,
         4.8454e-01, 2.2976e-01, 8.0981e-01, 8.4411e-01],
        [9.4887e-02, 6.7045e-01, 9.6068e-01, 8.2074e-03, 5.4129e-01, 5.8512e-01,
         7.4678e-01, 9.3809e-01, 7.6373e-01, 8.8639e-01],
        [6.4251e-01, 8.9216e-01, 7.6982e-01, 8.6086e-02, 1.0875e-01, 7.4228e-01,
         9.6265e-01, 9.6232e-01, 7.7961e-02, 5.1455e-01],
        [8.7728e-01, 9.8877e-01, 9.4753e-01, 4.1238e-02, 5.1584e-01, 2.5281e-01,
         6.5593e-01, 5.8543e-02, 1.8680e-01, 6.3729e-01],
        [3.6625e-01, 8.6149e-01, 8.3700e-02, 8.6026e-01, 6.8652e-01, 8.8982e-01,
         8.5585e-01, 5.2144e-01, 4.6238e-01, 2.9493e-02],
        [4.6114e-01, 5.8596e-01, 6.6695e-01, 5.6939e-05, 9.9837e-01, 4.7472e-02,
         2.3222e-01, 6.5587e-01, 2.8235e-01, 5.4755e-01],
        [5.9718e-02, 2.7248

In [25]:
# Choose a task in a job.
print(new_mat_t[2])
print(mask[2])

masked_mat = np.multiply(mat, mask)
# masked_mat_t = torch.tensor(masked_mat, dtype=torch.float
# masked_mat_t = torch.tensor(np.multiply(mat[2], mask[2]), dtype = torch.float)
# print(masked_mat_t)
print(masked_mat)

tensor([0.0949, 0.6705, 0.9607, 0.0082, 0.5413, 0.5851, 0.7468, 0.9381, 0.7637,
        0.8864])
[1. 0. 0. 1. 1. 0. 1. 0. 1. 1.]
[[2.926091e-02 2.928134e-01 5.200160e-01 7.219030e-01 6.449628e-01
  5.016564e-01 5.726451e-01 0.000000e+00 1.625655e-01 1.674371e-02]
 [0.000000e+00 1.533205e-01 9.855885e-01 0.000000e+00 6.384928e-02
  8.517345e-01 4.845381e-01 2.297567e-01 8.098114e-01 8.441080e-01]
 [9.488685e-02 0.000000e+00 0.000000e+00 8.207411e-03 5.412898e-01
  0.000000e+00 7.467761e-01 0.000000e+00 7.637320e-01 8.863927e-01]
 [6.425065e-01 8.921588e-01 7.698159e-01 0.000000e+00 1.087523e-01
  7.422812e-01 9.626469e-01 9.623218e-01 7.796134e-02 0.000000e+00]
 [8.772843e-01 9.887714e-01 0.000000e+00 4.123779e-02 5.158438e-01
  0.000000e+00 6.559289e-01 5.854266e-02 1.867967e-01 6.372885e-01]
 [3.662540e-01 8.614901e-01 8.369990e-02 8.602581e-01 6.865160e-01
  8.898230e-01 8.558457e-01 5.214423e-01 4.623825e-01 0.000000e+00]
 [4.611378e-01 5.859568e-01 0.000000e+00 0.000000e+00 9.98374

In [26]:
min_max_scaler = preprocessing.MinMaxScaler()

In [27]:
print(masked_mat)
masked_mat_scaled = min_max_scaler.fit_transform(masked_mat)

[[2.926091e-02 2.928134e-01 5.200160e-01 7.219030e-01 6.449628e-01
  5.016564e-01 5.726451e-01 0.000000e+00 1.625655e-01 1.674371e-02]
 [0.000000e+00 1.533205e-01 9.855885e-01 0.000000e+00 6.384928e-02
  8.517345e-01 4.845381e-01 2.297567e-01 8.098114e-01 8.441080e-01]
 [9.488685e-02 0.000000e+00 0.000000e+00 8.207411e-03 5.412898e-01
  0.000000e+00 7.467761e-01 0.000000e+00 7.637320e-01 8.863927e-01]
 [6.425065e-01 8.921588e-01 7.698159e-01 0.000000e+00 1.087523e-01
  7.422812e-01 9.626469e-01 9.623218e-01 7.796134e-02 0.000000e+00]
 [8.772843e-01 9.887714e-01 0.000000e+00 4.123779e-02 5.158438e-01
  0.000000e+00 6.559289e-01 5.854266e-02 1.867967e-01 6.372885e-01]
 [3.662540e-01 8.614901e-01 8.369990e-02 8.602581e-01 6.865160e-01
  8.898230e-01 8.558457e-01 5.214423e-01 4.623825e-01 0.000000e+00]
 [4.611378e-01 5.859568e-01 0.000000e+00 0.000000e+00 9.983741e-01
  0.000000e+00 2.322154e-01 6.558717e-01 2.823516e-01 5.475483e-01]
 [5.971761e-02 0.000000e+00 7.084642e-01 7.343728e-01 1

In [28]:
print(masked_mat_scaled)

[[2.960535e-02 2.961387e-01 5.276198e-01 7.613705e-01 6.405835e-01
  5.032287e-01 5.948652e-01 0.000000e+00 1.794757e-01 1.696039e-02]
 [0.000000e+00 1.550616e-01 1.000000e+00 0.000000e+00 4.959579e-02
  8.544039e-01 5.033393e-01 2.387524e-01 8.940485e-01 8.550312e-01]
 [9.600379e-02 0.000000e+00 0.000000e+00 8.656122e-03 5.351489e-01
  0.000000e+00 7.757529e-01 0.000000e+00 8.431759e-01 8.978631e-01]
 [6.500696e-01 9.022902e-01 7.810723e-01 0.000000e+00 9.526176e-02
  7.446076e-01 1.000000e+00 1.000000e+00 8.607094e-02 0.000000e+00]
 [8.876110e-01 1.000000e+00 0.000000e+00 4.349232e-02 5.092706e-01
  0.000000e+00 6.813805e-01 6.083480e-02 2.062274e-01 6.455353e-01]
 [3.705652e-01 8.712733e-01 8.492378e-02 9.072896e-01 6.828428e-01
  8.926118e-01 8.890546e-01 5.418586e-01 5.104798e-01 0.000000e+00]
 [4.665660e-01 5.926110e-01 0.000000e+00 0.000000e+00 1.000000e+00
  0.000000e+00 2.412259e-01 6.815513e-01 3.117220e-01 5.546339e-01]
 [6.042057e-02 0.000000e+00 7.188236e-01 7.745220e-01 1

In [29]:
# from sklearn.preprocessing import normalize
# from sklearn.preprocessing import StandardScaler

# masked_mat_scaled2 = normalize(masked_mat)
# print(masked_mat)
# print()

In [30]:
# print(np.sum(masked_mat_scaled[1]))
# t = np.sum(masked_mat_scaled[1])
# _masked_mat_scaled = masked_mat_scaled[1]/t
_masked_mat_scaled = np.ones((16,10))
for i in range(len(masked_mat_scaled)):
    t = np.sum(masked_mat_scaled[i])
    _masked_mat_scaled[i] = masked_mat_scaled[i]/t
print(_masked_mat_scaled)
for i in range(len(_masked_mat_scaled)):
    rowsum = np.sum(_masked_mat_scaled[i])
    print(rowsum)

[[8.339892e-03 8.342292e-02 1.486317e-01 2.144798e-01 1.804538e-01
  1.417606e-01 1.675748e-01 0.000000e+00 5.055871e-02 4.777778e-03]
 [0.000000e+00 3.407773e-02 2.197690e-01 0.000000e+00 1.089962e-02
  1.877715e-01 1.106184e-01 5.247038e-02 1.964841e-01 1.879093e-01]
 [3.041366e-02 0.000000e+00 0.000000e+00 2.742229e-03 1.695333e-01
  0.000000e+00 2.457558e-01 0.000000e+00 2.671152e-01 2.844399e-01]
 [1.236021e-01 1.715585e-01 1.485106e-01 0.000000e+00 1.811276e-02
  1.415773e-01 1.901368e-01 1.901368e-01 1.636525e-02 0.000000e+00]
 [2.200133e-01 2.478713e-01 0.000000e+00 1.078050e-02 1.262335e-01
  0.000000e+00 1.688947e-01 1.507920e-02 5.111785e-02 1.600097e-01]
 [6.443605e-02 1.515021e-01 1.476704e-02 1.577648e-01 1.187367e-01
  1.552125e-01 1.545940e-01 9.422153e-02 8.876522e-02 0.000000e+00]
 [1.212392e-01 1.539925e-01 0.000000e+00 0.000000e+00 2.598543e-01
  0.000000e+00 6.268359e-02 1.771041e-01 8.100232e-02 1.441240e-01]
 [1.846021e-02 0.000000e+00 2.196212e-01 2.366386e-01 5

In [66]:
masked_mat_scaled_t = torch.tensor(_masked_mat_scaled, dtype=torch.float)
for t in range(100):
    t = masked_mat_scaled_t.multinomial(num_samples=1)

    masked_mat_scaled_n = np.array(masked_mat_scaled_t)
    t_n = np.array(t)
    #print(masked_mat_scaled_n)
    print(t_n.reshape(1,16))
    for i in range(100):
        for j in range(len(masked_mat_scaled_n)):
            if masked_mat_scaled_n[j][t_n[j]] == 0:
                print("!!!!!!!!!!!!!!!!!")

!!!!!!!!!!!!
[[3 6 6 0 0 4 9 8 9 0 4 9 0 2 6 2]]
[[4 8 6 1 6 7 4 2 2 1 4 3 7 2 0 8]]
[[8 2 6 5 1 5 7 9 6 8 7 1 0 3 1 0]]
[[4 2 9 6 9 6 4 2 6 8 4 5 6 1 3 2]]
[[2 2 9 2 6 4 6 0 9 1 4 2 6 1 4 7]]
[[8 8 9 8 9 1 0 9 0 0 5 8 9 6 2 8]]
[[2 6 8 7 1 5 4 5 5 0 0 5 5 1 2 8]]
[[6 2 8 2 4 5 9 2 2 0 5 9 6 4 0 1]]
[[4 8 9 1 6 1 7 3 9 4 5 7 3 4 0 0]]
[[5 8 4 7 6 3 4 2 5 4 9 8 6 1 3 9]]
[[5 8 6 1 9 4 9 8 9 1 4 0 3 6 0 8]]
[[4 6 4 7 9 5 0 8 9 1 9 7 3 7 8 2]]
[[1 5 8 6 1 7 9 4 3 7 4 9 0 1 2 9]]
[[6 5 4 1 3 0 9 3 9 0 4 0 9 1 6 8]]
[[5 2 9 6 6 4 9 5 6 4 5 8 0 6 6 2]]
[[6 5 6 1 0 1 9 9 2 8 5 0 0 4 2 8]]
[[3 6 9 5 0 5 4 5 9 1 8 8 5 7 8 4]]
[[2 2 9 6 4 5 9 9 5 8 0 0 3 6 0 1]]
[[1 6 6 2 1 5 4 2 6 0 9 8 4 4 6 2]]
[[2 8 9 2 9 0 8 2 4 4 7 9 4 2 8 8]]
[[5 6 9 7 1 4 4 8 4 0 0 9 6 1 3 9]]
[[3 9 9 2 6 4 7 3 6 0 4 2 0 7 4 8]]
[[5 5 6 5 0 4 7 4 6 7 5 9 6 2 6 6]]
[[4 2 4 8 0 3 1 5 3 0 0 0 7 2 1 2]]
[[4 6 9 6 0 3 7 3 9 8 7 0 4 6 3 3]]
[[6 2 8 5 4 7 4 2 9 4 4 0 9 2 1 8]]
[[4 8 9 5 9 8 7 3 5 1 8 8 0 4 0 2]]
[[1 9 6 1 6 2 1