In [11]:
import numpy as np
import torch
from random import *
from sklearn import preprocessing
import pandas as pd
from sklearn.preprocessing import Normalizer

# np.set_printoptions(precision=6)

In [12]:
mat = np.random.random((16,10))
# mat = torch.tensor(dist, dtype=torch.float)

In [13]:
mat.shape

(16, 10)

In [14]:
# Make a mask
mask = np.ones((16,10))

for i in range(30):
    x = randint(0, 15)
    y = randint(0, 9)
    mask[x][y] = 0

mask[2][1] = 0
mask[2][2] = 0
mask[2][5] = 0
mask[2][7] = 0
mask

array([[1., 1., 0., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 0., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 0.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 1., 1., 1., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 0., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 1., 0.]])

In [15]:
new_mat_t = torch.tensor(mat, dtype=torch.float)
# please check for one task!

In [16]:
# Choose a task in a job.
print(new_mat_t[2])
print(mask[2])

masked_mat = np.multiply(mat, mask)
# masked_mat_t = torch.tensor(masked_mat, dtype=torch.float
# masked_mat_t = torch.tensor(np.multiply(mat[2], mask[2]), dtype = torch.float)
# print(masked_mat_t)
print(masked_mat)

tensor([0.4989, 0.9783, 0.3794, 0.0595, 0.2303, 0.3737, 0.0103, 0.7360, 0.9513,
        0.7373])
[0. 0. 0. 1. 1. 0. 1. 0. 1. 1.]
[[0.87425561 0.4501916  0.         0.99851745 0.51063018 0.4588697
  0.07142779 0.59342145 0.57982774 0.        ]
 [0.80830413 0.52995262 0.63148643 0.         0.59537586 0.0553945
  0.15503988 0.63831609 0.92222088 0.88347504]
 [0.         0.         0.         0.05948534 0.23031696 0.
  0.01030761 0.         0.95130108 0.73733963]
 [0.01573541 0.56244622 0.7784028  0.         0.02534604 0.75884412
  0.58916362 0.82123686 0.         0.84441432]
 [0.38211952 0.29060636 0.75801939 0.40467691 0.58272994 0.91294359
  0.55822158 0.24049484 0.         0.28412306]
 [0.67700798 0.92503246 0.30316933 0.00732718 0.80007517 0.79577291
  0.49677133 0.29719074 0.         0.51895282]
 [0.         0.79041712 0.61092002 0.89469253 0.54479647 0.56269912
  0.15217598 0.67362202 0.         0.08872634]
 [0.06738254 0.30081426 0.         0.88406261 0.09278739 0.71858903
  0.7885

In [ ]:
min_max_scaler = preprocessing.MinMaxScaler()

In [ ]:
print(masked_mat)
masked_mat_scaled = min_max_scaler.fit_transform(masked_mat)

In [ ]:
_masked_mat_scaled = np.ones((16,10))
for i in range(len(masked_mat_scaled)):
    t = np.sum(masked_mat_scaled[i])
    _masked_mat_scaled[i] = masked_mat_scaled[i]/t
print(_masked_mat_scaled)
for i in range(len(_masked_mat_scaled)):
    rowsum = np.sum(_masked_mat_scaled[i])
    print(rowsum)

In [ ]:
masked_mat_scaled_t = torch.tensor(_masked_mat_scaled, dtype=torch.float)
for t in range(100):
    t = masked_mat_scaled_t.multinomial(num_samples=1)

    masked_mat_scaled_n = np.array(masked_mat_scaled_t)
    t_n = np.array(t)
    #print(masked_mat_scaled_n)
    print(t_n.reshape(1,16))
    for i in range(100):
        for j in range(len(masked_mat_scaled_n)):
            if masked_mat_scaled_n[j][t_n[j]] == 0:
                print("!!!!!!!!!!!!!!!!!")

In [17]:
########################
#  only for one task.  #
########################
n_mat = np.array([-2.7531, -2.7391, -2.7252, -2.7484, -2.7834, -2.7706, -2.8017, -2.7864, -2.7768, -2.7830])
min_v = min(n_mat)
print(min_v)
n_mat = n_mat-min_v+0.01
print(n_mat)

-2.8017
[0.0586 0.0726 0.0865 0.0633 0.0283 0.0411 0.01   0.0253 0.0349 0.0287]


In [ ]:
new_mat_t = torch.tensor(n_mat, dtype=torch.float)
masked_mat_re = np.reshape(new_mat_t,(-1,1))

transformer = Normalizer().fit(masked_mat_re)
masked_mat_scaled_re = transformer.transform(masked_mat_re)
print(masked_mat_scaled_re)

In [ ]:
new_mat_t[2] = torch.tensor(n_mat, dtype=torch.float)
print(new_mat_t[2])
print(type(new_mat_t[2]))
print(mask[2])

masked_mat = np.multiply(new_mat_t[2], mask[2])
masked_mat_re = np.reshape(masked_mat,(-1,1))
print(masked_mat)
print(masked_mat_re)

In [7]:
from sklearn.preprocessing import Normalizer

# min_max_scaler = preprocessing.MinMaxScaler()

In [8]:
# masked_mat_scaled_re = min_max_scaler.fit_transform(masked_mat_re)
#masked_mat_scaled_re
transformer = Normalizer().fit(masked_mat_re)
masked_mat_scaled_re = transformer.transform(masked_mat_re)
print(masked_mat_scaled_re)

[[-0.]
 [-0.]
 [-0.]
 [-1.]
 [-1.]
 [-0.]
 [-1.]
 [-0.]
 [-0.]
 [-1.]]


In [41]:
t = np.sum(masked_mat_scaled_re[:])
t

4.058464756992105

In [42]:
_masked_mat_scaled = np.ones((len(masked_mat_re),1))
_masked_mat_scaled

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [33]:
_masked_mat_scaled[:] = masked_mat_scaled_re[:]/t
print(_masked_mat_scaled)
print("Check if sum is 1 ==== ",np.sum(_masked_mat_scaled[:]))

[[0.07821569]
 [0.        ]
 [0.        ]
 [0.2024731 ]
 [0.26485999]
 [0.        ]
 [0.15812928]
 [0.        ]
 [0.08389893]
 [0.212423  ]]
Check if sum is 1 ====  1.0


In [34]:
_masked_mat_scaled_t = torch.tensor(_masked_mat_scaled, dtype=torch.float)
_masked_mat_scaled_tre = np.reshape(_masked_mat_scaled_t,len(_masked_mat_scaled_t))
print(_masked_mat_scaled_tre)

tensor([0.0782, 0.0000, 0.0000, 0.2025, 0.2649, 0.0000, 0.1581, 0.0000, 0.0839,
        0.2124])


In [35]:
t = _masked_mat_scaled_tre.multinomial(num_samples=1)
print(t)
print(t[0].item())

tensor([4])
4


In [36]:
for i in range(1000):
    t = _masked_mat_scaled_tre.multinomial(num_samples=1)
    if _masked_mat_scaled_tre[t[0].item()] == 0:
        print("!!!!!!!!!!!!!!!!!")

AttributeError: 'numpy.ndarray' object has no attribute 'cpu'

In [59]:
import matplotlib as mpl
import matplotlib.pylab as plt
%matplotlib inline 
import torch
import torchvision.transforms.functional as F

In [64]:
state = np.random.random((200, 200))
print(state)

[[0.29897788 0.89864514 0.99766604 ... 0.39749961 0.52899936 0.22728527]
 [0.49788036 0.42616756 0.92585362 ... 0.47669379 0.88933529 0.11394485]
 [0.87931539 0.14511193 0.06418007 ... 0.66682744 0.29014925 0.13022923]
 ...
 [0.206438   0.87277499 0.62056648 ... 0.92428587 0.17225766 0.58424001]
 [0.52643797 0.33805272 0.53506457 ... 0.27139244 0.43899586 0.05739967]
 [0.51476429 0.25645613 0.52785158 ... 0.84680379 0.49049647 0.84563698]]


In [65]:
plt.show('/'+state+'.png', interpolation='nearest')

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

In [68]:
import matplotlib.image as mpimg
img=mpimg.imread('stinkbug.png')

FileNotFoundError: [Errno 2] No such file or directory: 'stinkbug.png'

In [66]:
state = F.to_pil_image(state)

TypeError: Input type float64 is not supported