In [9]:
import numpy as np
import torch
from random import *
from sklearn import preprocessing
import pandas as pd


# np.set_printoptions(precision=6)

In [10]:
mat = np.random.random((16,10))
# mat = torch.tensor(dist, dtype=torch.float)

In [11]:
mat.shape

(16, 10)

In [12]:
# Make a mask
mask = np.ones((16,10))

for i in range(30):
    x = randint(0, 15)
    y = randint(0, 9)
    mask[x][y] = 0

mask[2][1] = 0
mask[2][2] = 0
mask[2][5] = 0
mask[2][7] = 0
mask

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 0., 0., 1., 1., 1., 1., 0., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 1., 1.],
       [1., 0., 1., 1., 0., 1., 1., 0., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 0.]])

In [5]:
new_mat_t = torch.tensor(mat, dtype=torch.float)
# please check for one task!

In [ ]:
# Choose a task in a job.
print(new_mat_t[2])
print(mask[2])

masked_mat = np.multiply(mat, mask)
# masked_mat_t = torch.tensor(masked_mat, dtype=torch.float
# masked_mat_t = torch.tensor(np.multiply(mat[2], mask[2]), dtype = torch.float)
# print(masked_mat_t)
print(masked_mat)

In [ ]:
min_max_scaler = preprocessing.MinMaxScaler()

In [ ]:
print(masked_mat)
masked_mat_scaled = min_max_scaler.fit_transform(masked_mat)

In [ ]:
_masked_mat_scaled = np.ones((16,10))
for i in range(len(masked_mat_scaled)):
    t = np.sum(masked_mat_scaled[i])
    _masked_mat_scaled[i] = masked_mat_scaled[i]/t
print(_masked_mat_scaled)
for i in range(len(_masked_mat_scaled)):
    rowsum = np.sum(_masked_mat_scaled[i])
    print(rowsum)

In [ ]:
masked_mat_scaled_t = torch.tensor(_masked_mat_scaled, dtype=torch.float)
for t in range(100):
    t = masked_mat_scaled_t.multinomial(num_samples=1)

    masked_mat_scaled_n = np.array(masked_mat_scaled_t)
    t_n = np.array(t)
    #print(masked_mat_scaled_n)
    print(t_n.reshape(1,16))
    for i in range(100):
        for j in range(len(masked_mat_scaled_n)):
            if masked_mat_scaled_n[j][t_n[j]] == 0:
                print("!!!!!!!!!!!!!!!!!")

In [6]:
########################
#  only for one task.  #
########################
n_mat = [-2.7531, -2.7391, -2.7252, -2.7484, -2.7834, -2.7706, -2.8017, -2.7864, -2.7768, -2.7830]
new_mat_t[2] = torch.tensor(n_mat, dtype=torch.float)
print(new_mat_t[2])
print(type(new_mat_t[2]))
print(mask[2])

masked_mat = np.multiply(new_mat_t[2], mask[2])
masked_mat_re = np.reshape(masked_mat,(-1,1))
print(masked_mat)
print(masked_mat_re)

tensor([-2.7531, -2.7391, -2.7252, -2.7484, -2.7834, -2.7706, -2.8017, -2.7864,
        -2.7768, -2.7830])
<class 'torch.Tensor'>
[0. 0. 0. 1. 1. 0. 1. 0. 0. 1.]
tensor([-0.0000, -0.0000, -0.0000, -2.7484, -2.7834, -0.0000, -2.8017, -0.0000,
        -0.0000, -2.7830], dtype=torch.float64)
tensor([[-0.0000],
        [-0.0000],
        [-0.0000],
        [-2.7484],
        [-2.7834],
        [-0.0000],
        [-2.8017],
        [-0.0000],
        [-0.0000],
        [-2.7830]], dtype=torch.float64)


In [7]:
from sklearn.preprocessing import Normalizer

# min_max_scaler = preprocessing.MinMaxScaler()

In [8]:
# masked_mat_scaled_re = min_max_scaler.fit_transform(masked_mat_re)
#masked_mat_scaled_re
transformer = Normalizer().fit(masked_mat_re)
masked_mat_scaled_re = transformer.transform(masked_mat_re)
print(masked_mat_scaled_re)

[[-0.]
 [-0.]
 [-0.]
 [-1.]
 [-1.]
 [-0.]
 [-1.]
 [-0.]
 [-0.]
 [-1.]]


In [41]:
t = np.sum(masked_mat_scaled_re[:])
t

4.058464756992105

In [42]:
_masked_mat_scaled = np.ones((len(masked_mat_re),1))
_masked_mat_scaled

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [33]:
_masked_mat_scaled[:] = masked_mat_scaled_re[:]/t
print(_masked_mat_scaled)
print("Check if sum is 1 ==== ",np.sum(_masked_mat_scaled[:]))

[[0.07821569]
 [0.        ]
 [0.        ]
 [0.2024731 ]
 [0.26485999]
 [0.        ]
 [0.15812928]
 [0.        ]
 [0.08389893]
 [0.212423  ]]
Check if sum is 1 ====  1.0


In [34]:
_masked_mat_scaled_t = torch.tensor(_masked_mat_scaled, dtype=torch.float)
_masked_mat_scaled_tre = np.reshape(_masked_mat_scaled_t,len(_masked_mat_scaled_t))
print(_masked_mat_scaled_tre)

tensor([0.0782, 0.0000, 0.0000, 0.2025, 0.2649, 0.0000, 0.1581, 0.0000, 0.0839,
        0.2124])


In [35]:
t = _masked_mat_scaled_tre.multinomial(num_samples=1)
print(t)
print(t[0].item())

tensor([4])
4


In [36]:
for i in range(1000):
    t = _masked_mat_scaled_tre.multinomial(num_samples=1)
    if _masked_mat_scaled_tre[t[0].item()] == 0:
        print("!!!!!!!!!!!!!!!!!")