In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import scipy as sp

In [8]:
x = np.array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
                2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13,
                1,   0,  16,  15,   2,   4,  -7, -18,  -2,   2,  13,  13,  -2,
               -2,  -9, -13, -16,  20,  -4,  -3, -11,   8, -15,  -1,  -7,   4,
               -4, -10,   0,   5,   1,   4,  -5,  -2,  -5,  -2,  -7, -16,   2,
               -3, -15,   5,  -8,   1,   8,   2,  12, -11,   5,  -5,  -7,  -4])

In [9]:
sp.stats.describe(x)

DescribeResult(nobs=78, minmax=(-24, 23), mean=0.6923076923076923, variance=97.3066933066933, skewness=0.11586487731702556, kurtosis=-0.15461828136911615)

In [11]:
import torch
import torch.optim
import torch.nn as nn
import torch.nn.functional as F


In [14]:
list_of_ready = torch.tensor([1,2,3,4])

# target_distributions = torch.tensor(np.zeros((120, 3), dtype=np.float32)).to(device)

In [15]:
loss = nn.KLDivLoss(reduction="batchmean")

In [16]:
loss(list_of_ready, list_of_ready)

RuntimeError: log_vml_cpu not implemented for 'Long'

In [5]:
import numpy as np
import tensorflow as tf

def kl(x, y):
    X = tf.distributions.Categorical(probs=x)
    Y = tf.distributions.Categorical(probs=y)
    return tf.distributions.kl_divergence(X, Y)

a = np.array([1.25, 10.1, 20.65, 1000.8, 250.15, 90.05])
b = np.array([0.7, 0.2, 0.15, 0.15, 0.8, 0.15])
# a = np.array([0.25, 0.1, 0.65, 0.8, 0.15, 0.05])
# b = np.array([0.7, 0.2, 0.15, 0.15, 0.8, 0.15])
sess = tf.Session()

print(kl(a, b).eval(session=sess))

1.5290687110525873


In [33]:
def z_score_normalize(lst):
    normalized = []
    for value in lst:
        normalized_num = (value - np.mean(lst)) / np.std(lst)
        normalized.append(normalized_num)
    return normalized

z_score_normalize(a)

[-0.6400325724277038,
 -0.6151437188239609,
 -0.5854739554884254,
 2.17100173487414,
 0.05994885830355423,
 -0.3903003464376046]

In [62]:
def min_max_normalize(lst):
    normalized = []
    
    for value in lst:
        normalized_num = (value - min(lst)) / (max(lst) - min(lst))
        normalized.append(normalized_num)
    
    return np.array(normalized)

array([0. , 1. , 0.1, 0. , 0. , 0.6])

In [63]:
mask = np.array([0,1,0,0,0,0])

dag_nodes = np.zeros(mask.shape)
test = np.array([0.,10.,1.,0.,0.,6.])
dag_nodes[:len(test)] = test
dag_nodes = np.array(dag_nodes)
print(dag_nodes)

[ 0. 10.  1.  0.  0.  6.]


In [1]:
a = np.array([0.,  0.9,  0.1, 0.,  0.,  0.6])
b = np.array([0.7, 0.2, 0.15, 0.15, 0.8, 0.15])
print(a, type(a))
print(b, type(b))
sess = tf.Session()

print(kl(a, b).eval(session=sess))

NameError: name 'np' is not defined

In [2]:
import numpy as np
import tensorflow as tf

def kl(x, y):
    X = tf.distributions.Categorical(probs=x)
    Y = tf.distributions.Categorical(probs=y)
    return tf.distributions.kl_divergence(X, Y)

def min_max_normalize(lst):
    normalized = []
    
    for value in lst:
        normalized_num = (value - min(lst)) / (max(lst) - min(lst))
        normalized.append(normalized_num)
    
    return np.array(normalized)

def _with_mask(mask, lst):
    dag_nodes = np.zeros(mask.shape)
    dag_nodes[:len(lst)] = lst
    dag_nodes = dag_nodes * mask
    return dag_nodes

In [3]:

mask = np.array([0,1,0,0,0,0])
dag_nodes = np.zeros(mask.shape)
test = np.array([0.,10.,1.,0.,0.,6.])
dag_nodes[:len(test)] = test
dag_nodes = min_max_normalize(dag_nodes)
print(dag_nodes)


[0.  1.  0.1 0.  0.  0.6]


In [7]:
mask = np.array([0,1,0,0,0,0])
dag_nodes = np.zeros(mask.shape)
test = np.array([0.,10.,1.,0.,0.])

dag_nodes[:len(test)] = test
dag_nodes = dag_nodes * mask
print(dag_nodes)

[ 0. 10.  0.  0.  0.  0.]


In [18]:
mask = np.array([0,1,0,0,0,0])
test = np.array([0.,10.,1.,0.,0.])
dag_nodes = min_max_normalize(_with_mask(mask, test))
print(dag_nodes)

[0. 1. 0. 0. 0. 0.]


In [19]:
b = np.array([0.7, 0.2, 0.15, 0.15, 0.8, 0.15])
sess = tf.Session()

print(kl(dag_nodes, b).eval(session=sess))


Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
nan


In [16]:
b = np.array([1,2,3])
test = np.log(np.array([11.,10.,1.,6.,8.,9.]))
sess = tf.Session()
np.log(0)
print(kl(mask, test).eval(session=sess))


nan


/Users/jeongsooha/anaconda3/envs/torch12/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


In [22]:
np.log(1e-9)

-20.72326583694641

In [10]:
sess = tf.Session()

ready_tasks_list = np.array([1,2,3])
node_output = np.array([0.1,0.8,0.6])
node_output = tf.nn.softmax(node_output, dim=-1).eval(session=sess)

ranku = np.array([0.,20.,10.,11.,8.,9., 0, 0])
ranku = ranku[ready_tasks_list[:]]
ranku = tf.nn.softmax(ranku, dim=-1).eval(session=sess)

print(ranku)

[9.99831219e-01 4.53922671e-05 1.23388975e-04]


In [12]:
# test = min_max_normalize(test)
print(ranku)
print(node_output)
kl(ranku, node_output).eval(session=sess)

[9.99831219e-01 4.53922671e-05 1.23388975e-04]
[0.21447841 0.43190648 0.35361511]


1.537719515858968