In [34]:
import numpy as np
total_pes = 3
total_num_nodes = 11

In [35]:
pe_valid_mask = np.zeros((1,total_num_nodes, total_pes))

In [43]:
pe_valid_mask[0,2,0]=1
pe_valid_mask

array([[[0., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
np.zeros([1, total_num_nodes])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.zeros([1,total_num_nodes, total_pes])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [49]:
a = np.ones([3,5])

In [53]:
a[0][1]=1
a[0][2]=2
a[1][1]=2
a[2][1]=3
a

array([[1., 1., 2., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 3., 1., 1., 1.]])

In [54]:
b = a[:,:3]

In [3]:
import numpy as np
np.zeros([2,4]) -1

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

In [7]:
node_inputs = np.ones((1,4,5))
node_valid_mask = np.zeros((1,4))-1
node_inputs, node_valid_mask

(array([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]), array([[-1., -1., -1., -1.]]))

In [8]:
node_inputs + node_valid_mask

ValueError: operands could not be broadcast together with shapes (1,4,5) (1,4) 

In [50]:
import tensorflow as tf
import numpy as np
sess = tf.Session()

In [51]:
pe_mask = np.array([[[1,1,1,0],[0,0,0,0],[1,1,1,0],[1,1,1,0],[0,0,0,0]]],  dtype=np.float32)
pe_mask.shape

(1, 5, 4)

In [52]:
# pe_input = np.array([[[0.41],[0.59],[1.04],[0.30]]],  dtype=np.float32)
pe_input = np.array([[[-0.61],[-0.66],[-0.49],[0.08]]],  dtype=np.float32)
pe_input = np.reshape(pe_input,[1, -1])
pe_input.shape

(1, 4)

In [53]:
pe_mask = (pe_mask-1)*10000.0
masked_pe = pe_input+pe_mask
masked_pe

array([[[-6.100000e-01, -6.600000e-01, -4.900000e-01, -9.999920e+03],
        [-1.000061e+04, -1.000066e+04, -1.000049e+04, -9.999920e+03],
        [-6.100000e-01, -6.600000e-01, -4.900000e-01, -9.999920e+03],
        [-6.100000e-01, -6.600000e-01, -4.900000e-01, -9.999920e+03],
        [-1.000061e+04, -1.000066e+04, -1.000049e+04, -9.999920e+03]]],
      dtype=float32)

In [54]:
masked_pe.shape

(1, 5, 4)

In [55]:
pe_outputs = tf.nn.softmax(masked_pe, dim=-1)
pe_outputs.shape

TensorShape([Dimension(1), Dimension(5), Dimension(4)])

In [56]:
logits = tf.math.log(pe_outputs)
logits

<tf.Tensor 'Log_25:0' shape=(1, 5, 4) dtype=float32>

In [57]:
noise = tf.random.uniform(tf.shape(pe_outputs))
noise

<tf.Tensor 'random_uniform_5:0' shape=(1, 5, 4) dtype=float32>

In [58]:
logits - tf.math.log(-tf.math.log(noise))

<tf.Tensor 'sub_10:0' shape=(1, 5, 4) dtype=float32>

In [59]:
pe_acts = tf.argmax(logits - tf.math.log(-tf.math.log(noise)), 2)
pe_acts

<tf.Tensor 'ArgMax_5:0' shape=(1, 5) dtype=int64>

In [60]:
sess.run(pe_acts)

array([[0, 0, 1, 2, 0]])

In [65]:
pe_act_probs = pe_input = np.array([[[-0.61,-0.66,-0.49,0.08],[-0.61,-0.66,-0.49,0.08],[-0.61,-0.66,-0.49,0.08],[-0.61,-0.66,-0.49,0.08],[-0.61,-0.66,-0.49,0.08]]],  dtype=np.float32)
pe_act_probs.shape

(1, 5, 4)

In [66]:
pe_act_vec = np.array([[[1,1,1,0],[0,0,0,0],[1,1,1,0],[1,1,1,0],[0,0,0,0]]],  dtype=np.float32)
pe_act_vec.shape

(1, 5, 4)

In [68]:
sess.run(tf.reduce_sum(tf.multiply(pe_act_probs, pe_act_vec),reduction_indices=1, keep_dims=True))

array([[[-1.83, -1.98, -1.47,  0.  ]]], dtype=float32)

In [72]:
import networkx as nx
import numpy as np
def random_attack( g ):
        g.remove_node( np.random.randint( 0, g.number_of_nodes() ) );

G = nx.erdos_renyi_graph(100,0.15);
for i in range(0, 30):
        random_attack( G );

NetworkXError: The node 7 is not in the graph.

In [75]:
reshape = np.ones((1,4))
reshape[0,1]=2
mask = np.zeros((1,10,4))

In [76]:
reshape+mask

array([[[1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.],
        [1., 2., 1., 1.]]])

In [77]:
# self.selected_pe_prob = 
# tf.reduce_sum(tf.multiply(self.pe_act_probs, self.pe_act_vec),reduction_indices=1, keep_dims=True)

In [91]:
pe_act_probs = np.zeros((2,10,4))
pe_act_vec[0,0,3]=1
pe_act_vec[1,1,0]=1

(2, 10, 4)


In [92]:
pe_act_vec = np.zeros((2,10,4))
pe_act_vec[0,0,3]=1
pe_act_vec[1,1,0]=1

(2, 10, 4)


In [93]:
selected_pe_prob = tf.reduce_sum(tf.multiply(pe_act_probs, pe_act_vec),reduction_indices=1, keep_dims=True)

In [94]:
sess.run(selected_pe_prob).shape

(2, 1, 4)

In [95]:
node_act_probs = np.zeros((2,10))
node_act_vec = np.zeros((2,10))

In [96]:
selected_node_prob = tf.reduce_sum(tf.multiply(node_act_probs, node_act_vec),reduction_indices=1, keep_dims=True)

In [97]:
sess.run(selected_node_prob).shape

(2, 1)

In [99]:
tf.math.log(selected_node_prob + selected_pe_prob)

<tf.Tensor 'Log_30:0' shape=(2, 2, 4) dtype=float64>

In [ ]:
eps=np.ones(())

In [109]:
for i in range(1,4):
    print(i)

1
2
3


In [ ]:
# tf.reduce_sum(tf.multiply(tf.math.log(self.selected_node_prob + self.selected_pe_prob+self.eps), -self.adv))

In [ ]:
selected_node_prob = tf.reduce_sum(tf.multiply(node_act_probs, node_act_vec),reduction_indices=1, keep_dims=True)

In [159]:
valid = np.ones((1,10,4))

pe_output = np.array([[1.,2.,3.,4]])
pe_output = np.reshape(pe_output, [1, -1])

print(pe_output)
print(pe_output.shape, valid.shape)

[[1. 2. 3. 4.]]
(1, 4) (1, 10, 4)


In [160]:
masked = pe_output+valid
print(masked, masked.shape)

[[[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]] (1, 10, 4)


In [161]:
batch = 19
valid = np.zeros((batch,20,4))
pe_output = np.arange(76.0)
# pe_output = np.range((batch,4,1))
pe_output = np.reshape(pe_output, [batch,1, -1])
print(pe_output.shape, valid.shape)

(19, 1, 4) (19, 20, 4)


In [163]:
masked = pe_output+valid
print(masked, masked.shape)

[[[ 0.  1.  2.  3.]
  [ 0.  1.  2.  3.]
  [ 0.  1.  2.  3.]
  ...
  [ 0.  1.  2.  3.]
  [ 0.  1.  2.  3.]
  [ 0.  1.  2.  3.]]

 [[ 4.  5.  6.  7.]
  [ 4.  5.  6.  7.]
  [ 4.  5.  6.  7.]
  ...
  [ 4.  5.  6.  7.]
  [ 4.  5.  6.  7.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [ 8.  9. 10. 11.]
  [ 8.  9. 10. 11.]
  ...
  [ 8.  9. 10. 11.]
  [ 8.  9. 10. 11.]
  [ 8.  9. 10. 11.]]

 ...

 [[64. 65. 66. 67.]
  [64. 65. 66. 67.]
  [64. 65. 66. 67.]
  ...
  [64. 65. 66. 67.]
  [64. 65. 66. 67.]
  [64. 65. 66. 67.]]

 [[68. 69. 70. 71.]
  [68. 69. 70. 71.]
  [68. 69. 70. 71.]
  ...
  [68. 69. 70. 71.]
  [68. 69. 70. 71.]
  [68. 69. 70. 71.]]

 [[72. 73. 74. 75.]
  [72. 73. 74. 75.]
  [72. 73. 74. 75.]
  ...
  [72. 73. 74. 75.]
  [72. 73. 74. 75.]
  [72. 73. 74. 75.]]] (19, 20, 4)


In [165]:
pe_input = np.zeros((160,4))
batch = 40
pe_input = np.reshape(pe_input,(batch, -1, 4))
pe_input.shape

(40, 4, 4)

In [205]:
sess = tf.Session()
a0 = tf.reshape(tf.range(12), (3, 4))
sess.run(a0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [206]:
a1, a2 = tf.split(a0, num_or_size_splits=2, axis=1)  # 가로축(axis=1)을 따라 2개로 분할 
print(sess.run(a1))
print(a1.shape)
print(sess.run(a2))
print(a2.shape)

[[0 1]
 [4 5]
 [8 9]]
(3, 2)
[[ 2  3]
 [ 6  7]
 [10 11]]
(3, 2)


In [207]:
tile = tf.tile(a1, [1, 3])
print(sess.run(tile))  # 가로축(axis=1)을 따라 3개로 복사-붙이기
print(tile.shape)

[[0 1 0 1 0 1]
 [4 5 4 5 4 5]
 [8 9 8 9 8 9]]
(3, 6)


In [209]:
con = tf.concat([a1, a2], 0)
print(sess.run(con)) # 가로축(axis=1)을 따라 a1, a2를 합치기
print(con.shape)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [ 2  3]
 [ 6  7]
 [10 11]]
(6, 2)


In [219]:
sess = tf.Session()
a0 = tf.reshape(tf.range(12), (4, 3))
sess.run(a0)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)

In [220]:
a1, a2 = tf.split(a0, num_or_size_splits=2, axis=0)  # 가로축(axis=1)을 따라 2개로 분할 
print(sess.run(a1))
print(a1.shape)
print(sess.run(a2))
print(a2.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)
[[ 6  7  8]
 [ 9 10 11]]
(2, 3)


In [221]:
tile = tf.tile(a1, [1, 3])
print(sess.run(tile))  # 가로축(axis=1)을 따라 3개로 복사-붙이기
print(tile.shape)

[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]
(2, 9)


In [222]:
con = tf.concat([a1, a2], 2)
print(sess.run(con)) # 가로축(axis=1)을 따라 a1, a2를 합치기
print(con.shape)

ValueError: Shape must be at least rank 3 but is rank 2 for 'concat_9' (op: 'ConcatV2') with input shapes: [2,3], [2,3], [] and with computed input tensors: input[2] = <2>.

In [247]:
sess = tf.Session()
a0 = tf.reshape(tf.range(18), (3, 3, 2))
a1 = tf.reshape(tf.range(9), (3, 3, 1))
print(sess.run(a0))
print(a0.shape)
print(sess.run(a1))
print(a1.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
(3, 3, 2)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]
(3, 3, 1)


In [248]:
con = tf.concat([a0, a1], axis=2)
print(sess.run(con))
print(con.shape)

[[[ 0  1  0]
  [ 2  3  1]
  [ 4  5  2]]

 [[ 6  7  3]
  [ 8  9  4]
  [10 11  5]]

 [[12 13  6]
  [14 15  7]
  [16 17  8]]]
(3, 3, 3)
